title: Copy and Paste Example For Secure Coding
author: Michael Hegglin
 
description: > # this means to ignore newlines until "baseurl:"
  The purpose is to make easy copy and paste examples of secure methods 
  in many languages.  For example you want to execute a shell command in C++,
  however, you don't know how to do that securely.  This blog is here to
  help!  Most of the examples are taken from books, and cleaned up to 
  run with copy and pasting.
# social links
github_username:  hegglinmichael # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima


